version: "3"

services:
# moqui-base
    moqui-base:
        image: "pavlovmedia/pavlov-moqui-base-container"
        ports:
            - "8280:8080"
        stdin_open: true
        networks:
            default:
                aliases:
                    - moqui-base
# Volumes
volumes:
    moqui-base-configured:
        external: true
